In [9]:
import numpy as np

In [10]:
a = [0, 1, 2]

In [39]:
np.array(a)

array([0, 1, 2])

In [14]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(0,5,2) # every 2 steps

array([0, 2, 4])

In [17]:
np.zeros(2)

array([ 0.,  0.])

In [18]:
np.zeros([2,3]) # or np.zeros((2,3)), but not np.zeros(2,3)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [25]:
np.zeros([2,3])[0]

array([ 0.,  0.,  0.])

In [26]:
np.ones(2)

array([ 1.,  1.])

In [29]:
np.linspace(2, 5, 7) # start, stop, # of steps

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [30]:
np.random.randint(0, 10) # [0, 10)

2

In [31]:
np.random.randint(0, 10, (2,3)) # 2x3 matrix

array([[6, 8, 0],
       [9, 7, 9]])

In [35]:
np.random.normal(2, 7, (2,2)) # mean, stdev, size

array([[ 10.37897076,  -2.57979207],
       [  8.53762547,  -0.82919429]])

In [41]:
np.random.seed(999)
a = np.random.randint(0, 100, 10)
print(a)

[64 92 97 72 97 91 31 89 51 16]


In [42]:
a = np.random.randint(0, 100, 10) # in jupyter a seed only works in current block
print(a)

[ 8  8 48 69 66 11 11 21 87 50]


In [43]:
a.mean()

37.899999999999999

In [45]:
a.std()

28.172504326026822

In [46]:
a.max()

87

In [47]:
a.argmax() # index of max val, starts from 0

8

In [57]:
print(a)

b = a.reshape(2,5) # row x col has to equal to length of a
print(b)
print(a)

[ 8  8 48 69 66 11 11 21 87 50]
[[ 8  8 48 69 66]
 [11 11 21 87 50]]
[ 8  8 48 69 66 11 11 21 87 50]


In [70]:
a.shape # no perentesis

(10,)

In [71]:
b.shape

(2, 5)

In [72]:
b.size # no perentesis

10

In [74]:
c = np.arange(0,25).reshape(5,5)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [76]:
c[2,0]

10

In [77]:
c[:,0] # for all rows, get the 0th column

array([ 0,  5, 10, 15, 20])

In [79]:
c[0:2, 0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [81]:
c[0:2, 2]

array([2, 7])

In [82]:
c > 6

array([[False, False, False, False, False],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [84]:
c[c > 6]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24])