In [1]:
import tensorflow as tf

In [2]:
my_tensor = tf.random_uniform((4,4),0,1)
my_var = tf.Variable(initial_value=my_tensor)
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [3]:
init = tf.global_variables_initializer() # variables have to be initialized before use !!!!!!

In [6]:
with tf.Session() as sess:
    init.run()
    z = my_var.eval()

print(z)

[[ 0.41101241  0.84301639  0.71443224  0.61550546]
 [ 0.76456952  0.97850966  0.36241555  0.13796139]
 [ 0.00997758  0.10615504  0.01060879  0.35380936]
 [ 0.25558317  0.25562286  0.69456482  0.55608344]]


In [7]:
x = tf.placeholder(tf.float32) # place holders must specify input type, in this case is float32
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    
print(result)

[ 2.  4.  6.]


In [9]:
tf.placeholder(tf.int32,shape=(None,5))

<tf.Tensor 'Placeholder_2:0' shape=(?, 5) dtype=int32>