In [2]:
import tensorflow as tf

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [8]:
result = hello + world
print(result)
type(result)

Tensor("add_2:0", shape=(), dtype=string)


tensorflow.python.framework.ops.Tensor

In [10]:
with tf.Session() as sess: # don't need sess.close() if we are under the "with"
    result = sess.run(hello+world)

In [11]:
result # the "b" in front of the result below means "byte array" in python

b'HelloWorld'

In [12]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [13]:
const = tf.constant(10)
fill_mat = tf.fill((4,4),10) # fill a 4x4 matrix with 10s
myzeros = tf.zeros((4,4)) # make a 4x4 matrix of zeros
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5) # normally distributted
myrandu = tf.random_uniform((4,4),minval=0,maxval=1) # uniformly distributted

In [15]:
my_ops = [const,fill_mat,myzeros,myrandn,myrandu]

In [17]:
with tf.Session() as sess:
    for op in my_ops:
        print(op.eval())
        print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 0.64433664  0.09322438  0.23227914 -0.11999042]
 [-0.24156569 -0.15029997  1.09797394 -0.11183072]
 [ 0.00120449  1.00130367  0.18064383 -0.3049866 ]
 [ 0.5750044  -0.15283675  0.66381043  0.36290136]]


[[ 0.64466047  0.40897691  0.63578463  0.98001707]
 [ 0.85080445  0.6697588   0.10778522  0.37106609]
 [ 0.6377269   0.92309022  0.67419648  0.56968367]
 [ 0.94136977  0.93573141  0.65895796  0.9727627 ]]




In [21]:
a = tf.constant([ [1,2],[3,4] ]) # inner-most brackets = rows, variables inside the inner-most brackets = columns
# tf.constant([1,2], [3,4]) doesn't work

In [20]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [22]:
b = tf.constant([[10],[100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [23]:
result = tf.matmul(a,b)
with tf.Session() as sess:
    result.eval()

In [24]:
result

<tf.Tensor 'MatMul:0' shape=(2, 1) dtype=int32>